/*
 * quiz.h
 * This file contains all the actual quizzes- plus the quiz item object.
 * Author: Paul Clarke
 *
 */

#ifndef __QUIZ_H_INCLUDED__
#define __QUIZ_H_INCLUDED__


#include "theory.h"
#include <vector>
#include <string>

struct ChordQItem {
    std::vector<Note> notevec;
    std::string name;
};

/* Given a chord, generate a ChordQItem of that chord transposed to a random
   key, and put randomly somewhere in the range between midi notes min_mn and
   max_mn. The name of the QItem will be generated by a given suffix appended to
   the key name. If show_lowest is true, then the identity of the lowest
   note will be appended to this name.*/
ChordQItem transpose_q(std::vector<Note> chord, int min_mn, int max_mn,
                       std::string suffix, int flatsharp_limit=6, bool show_lowest=true);

/* triad in a random key and inversion */
ChordQItem major_triad_quiz();
/* root positioion major and minor seventh chords */
ChordQItem quiz_root_pos_majmin_7ths();

#endif
